// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/punto4.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class punto4 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=3;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,punto4.createTransducer()));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"main",$line);
    }
  }
  public static Integer hola=null;
  static {
    int $line=0;
    $line=5;
    $try:try {
      hola=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,null,$line);
    }
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=7;
      Object Q=$fix(GCollections.asSet("Inicio","Error","Numero","?",":","minus","mayus","f","a","i","l","i1","s","v","a1","r","a2","t","o","m","n","u","m","b","e","r"));
      $line=8;
      Object CE=$fix(GCollections.asSet(' '));
      $line=9;
      Object \u03A3=$fix($opUnionY($opUnionY($opUnionY($opIntvlY('a','z'),$opIntvlY('A','Z')),$opIntvlY('0','9')),GCollections.asSet('?',':')));
      $line=10;
      Object q_0=$fix("Inicio");
      $line=11;
      Object F=$fix(GCollections.asSet("Inicio"));
      $line=12;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3,q_0,F,new GMethod(punto4.class,"\u03B4"),new GMethod(punto4.class,"g"),new GMethod(punto4.class,"h")});
      if (true) break $try;
      $line=13;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=15;
      if ($opEqualY(q,"Inicio")) {
        $line=16;
        if ($opEqualY(\u03C3,'?')) {
          $line=17;
          $result="?";
          if (true) break $try;
        }
        else {
          $line=18;
          if ($opEqualY(\u03C3,':')) {
            $line=19;
            $result=":";
            if (true) break $try;
          }
          else {
            $line=20;
            if ($opMembrY(\u03C3,$opIntvlY('0','9'))) {
              $line=21;
              $result="Numero";
              if (true) break $try;
            }
            else {
              $line=22;
              if ($opEqualY(\u03C3,'i')) {
                $line=23;
                $result="i1";
                if (true) break $try;
              }
              else {
                $line=24;
                if ($opMembrY(\u03C3,$opIntvlY('A','Z'))) {
                  $line=25;
                  $result="mayus";
                  if (true) break $try;
                }
                else {
                  $line=26;
                  if ($opEqualY(\u03C3,'f')) {
                    $line=27;
                    $result="f";
                    if (true) break $try;
                  }
                  else {
                    $line=30;
                    $result="Error";
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      else {
        $line=32;
        if ($opEqualY(q,"Numero")) {
          $line=33;
          if ($opEqualY(\u03C3,'?')) {
            $line=34;
            $result="?";
            if (true) break $try;
          }
          else {
            $line=35;
            if ($opEqualY(\u03C3,':')) {
              $line=36;
              $result=":";
              if (true) break $try;
            }
            else {
              $line=37;
              if ($opMembrY(\u03C3,$opIntvlY('0','9'))) {
                $line=38;
                $result="Numero";
                if (true) break $try;
              }
              else {
                $line=39;
                if ($opMembrY(\u03C3,$opIntvlY('0','9'))) {
                  $line=40;
                  $result="Inicio";
                  if (true) break $try;
                }
                else {
                  $line=42;
                  $result="Error";
                  if (true) break $try;
                }
              }
            }
          }
        }
        else {
        }
      }
      $line=47;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=49;
      $result="";
      if (true) break $try;
      $line=50;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=53;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"h",$line);
    }
    return $result;
  }
}
