// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/punto2.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class punto2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Character letra=null;
  static {
    int $line=0;
    $line=5;
    $try:try {
      letra=$defaultValue(Character.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,null,$line);
    }
  }
  public static Boolean primera=null;
  static {
    int $line=0;
    $line=6;
    $try:try {
      primera=$defaultValue(Boolean.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=10;
      Object Q=$fix(GCollections.asSet('0','1','2','5'));
      $line=11;
      Object \u03A3=$fix($opUnionY(GCollections.asSet(' ','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','.'),$opIntvlY('0','9')));
      $line=12;
      Object qI=$fix('0');
      $line=13;
      Object F=$fix(GCollections.asSet('5'));
      $line=15;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3,qI,F,new GMethod(punto2.class,"\u03B4"),new GMethod(punto2.class,"g"),new GMethod(punto2.class,"h")}));
      $line=17;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
      $line=19;
      letra=$cast(Character.class,$fix(' '));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,"main",$line);
    }
  }
  public static Object h(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=25;
      if ((($opEqualY(q,'1')&&!$opMembrY(x,GCollections.asSet(' ','.')))&&!$opMembrY(x,$opIntvlY('0','9')))) {
        $line=28;
        $result=$opAdditY($opAdditY(' ',""),letra);
        if (true) break $try;
      }
      else {
        $line=30;
        if ($opEqualY(q,'0')) {
          $line=31;
          $result=letra;
          if (true) break $try;
        }
        else {
          $line=32;
          if (($opEqualY(q,'2')&&$opMembrY(x,$opIntvlY('0','9')))) {
            $line=34;
            $result=letra;
            if (true) break $try;
          }
          else {
            $line=35;
            if ((($opEqualY(q,'2')&&$opMembrY(x,$opIntvlY('a','z')))&&!$opEqualY(x,letra))) {
              $line=38;
              $result=x;
              if (true) break $try;
            }
            else {
              $line=39;
              if (($opEqualY(q,'1')&&$opEqualY(x,'.'))) {
                $line=41;
                $result='.';
                if (true) break $try;
              }
              else {
                $line=45;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=47;
      $rethrow(new RuntimeException("The function \"h(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,"h",$line);
    }
    return $result;
  }
  public static Object \u03B4(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=51;
      if ($opMembrY(q,GCollections.asSet('1','0'))) {
        $line=53;
        if ($opMembrY(x,$opIntvlY('0','9'))) {
          $line=54;
          $result='1';
          if (true) break $try;
        }
        else {
          $line=55;
          if ((!$opEqualY(x,'.')&&!$opEqualY(x,' '))) {
            $line=56;
            letra=$cast(Character.class,$fix(x));
            $line=57;
            $result='2';
            if (true) break $try;
          }
          else {
            $line=60;
            $result='5';
            if (true) break $try;
          }
        }
      }
      else {
        $line=62;
        if ($opEqualY(q,'2')) {
          $line=63;
          if ($opEqualY(x,'.')) {
            $line=65;
            $result='5';
            if (true) break $try;
          }
          else {
            $line=67;
            if ($opEqualY(x,letra)) {
              $line=68;
              $result='1';
              if (true) break $try;
            }
            else {
              $line=70;
              $result='2';
              if (true) break $try;
            }
          }
        }
        else {
          $line=73;
          primera=$cast(Boolean.class,$fix(true));
          $line=74;
          $result='5';
          if (true) break $try;
        }
      }
      $line=76;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=79;
      $result="";
      if (true) break $try;
      $line=80;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto2.class,"g",$line);
    }
    return $result;
  }
}
