// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/punto4.gold"
import gold.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class punto4 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=2;
      System.out.println($message(new Object[]{"Hello World"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto4.class,"main",$line);
    }
  }
}
