// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/punto1.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class punto1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Integer palabras=null;
  static {
    int $line=0;
    $line=4;
    $try:try {
      palabras=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,null,$line);
    }
  }
  public static Integer letras=null;
  static {
    int $line=0;
    $line=5;
    $try:try {
      letras=$defaultValue(Integer.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,null,$line);
    }
  }
  public static Character letra=null;
  static {
    int $line=0;
    $line=6;
    $try:try {
      letra=$defaultValue(Character.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,null,$line);
    }
  }
  public static Character letraTemp=null;
  static {
    int $line=0;
    $line=7;
    $try:try {
      letraTemp=$defaultValue(Character.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,null,$line);
    }
  }
  public static Boolean primera=null;
  static {
    int $line=0;
    $line=8;
    $try:try {
      primera=$defaultValue(Boolean.class);
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,null,$line);
    }
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=11;
      Object Q=$fix(GCollections.asSet('1','2','5'));
      $line=12;
      Object \u03A3=$fix($opUnionY(GCollections.asSet(' ','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','.'),$opIntvlY('0','9')));
      $line=13;
      Object qI=$fix('1');
      $line=14;
      Object F=$fix(GCollections.asSet('5'));
      $line=15;
      Object M=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3,qI,F,new GMethod(punto1.class,"\u03B4"),new GMethod(punto1.class,"g"),new GMethod(punto1.class,"h")}));
      $line=17;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
      $line=18;
      palabras=$cast(Integer.class,$fix(0));
      $line=19;
      letras=$cast(Integer.class,$fix(0));
      $line=20;
      Object modulo1=$fix(0);
      $line=21;
      Object modulo2=$fix(0);
      $line=22;
      primera=$cast(Boolean.class,$fix(true));
      $line=23;
      letraTemp=$cast(Character.class,$fix(' '));
      $line=24;
      letra=$cast(Character.class,$fix(' '));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,"main",$line);
    }
  }
  public static Object h(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=27;
      if (($opEqualY(q,'1')&&!$opMembrY(x,GCollections.asSet(' ','.')))) {
        $line=28;
        $result=letra;
        if (true) break $try;
      }
      else {
        $line=29;
        if (($opEqualY(q,'2')&&$opEqualY(x,' '))) {
          $line=30;
          $result=$opAdditY($opAdditY(letra,""),$opModulY($opAdditY(letras,palabras),3));
          if (true) break $try;
        }
        else {
          $line=31;
          if (($opEqualY(q,'2')&&$opEqualY(x,letra))) {
            $line=32;
            $result=$opModulY(letras,5);
            if (true) break $try;
          }
          else {
            $line=33;
            if (($opEqualY(q,'2')&&!$opMembrY(x,GCollections.asSet(' ',letra,'.')))) {
              $line=34;
              $result=letraTemp;
              if (true) break $try;
            }
            else {
              $line=35;
              if (($opEqualY(q,'2')&&$opEqualY(x,'.'))) {
                $line=36;
                $result=$opAdditY($opAdditY($opAdditY(letra,""),$opModulY($opAdditY(letras,palabras),3)),'.');
                if (true) break $try;
              }
              else {
                $line=38;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=40;
      $rethrow(new RuntimeException("The function \"h(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,"h",$line);
    }
    return $result;
  }
  public static Object \u03B4(Object q, Object x) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=43;
      if ($opEqualY(q,'1')) {
        $line=44;
        if ((!$opEqualY(x,'.')&&!$opEqualY(x,' '))) {
          $line=45;
          if ($opEqualY(primera,true)) {
            $line=46;
            palabras=$cast(Integer.class,$fix(1));
            $line=47;
            primera=$cast(Boolean.class,$fix(false));
          }
          else {
            $line=49;
            palabras=$cast(Integer.class,$fix($opAdditY(palabras,1)));
          }
          $line=51;
          letra=$cast(Character.class,$fix(x));
          $line=52;
          letras=$cast(Integer.class,$fix(1));
          $line=53;
          $result='2';
          if (true) break $try;
        }
        else {
          $line=55;
          primera=$cast(Boolean.class,$fix(true));
          $line=56;
          $result='5';
          if (true) break $try;
        }
      }
      else {
        $line=58;
        if ($opEqualY(q,'2')) {
          $line=59;
          letraTemp=$cast(Character.class,$fix(x));
          $line=60;
          if ($opEqualY(x,' ')) {
            $line=61;
            $result='1';
            if (true) break $try;
          }
          else {
            $line=62;
            if ($opEqualY(x,'.')) {
              $line=63;
              primera=$cast(Boolean.class,$fix(true));
              $line=64;
              $result='5';
              if (true) break $try;
            }
            else {
              $line=65;
              if ($opEqualY(x,letra)) {
                $line=66;
                letras=$cast(Integer.class,$fix($opAdditY(letras,1)));
                $line=67;
                $result='2';
                if (true) break $try;
              }
              else {
                $line=69;
                letras=$cast(Integer.class,$fix($opAdditY(letras,1)));
                $line=70;
                $result='2';
                if (true) break $try;
              }
            }
          }
        }
        else {
          $line=73;
          primera=$cast(Boolean.class,$fix(true));
          $line=74;
          $result='5';
          if (true) break $try;
        }
      }
      $line=76;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,x:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=79;
      $result="";
      if (true) break $try;
      $line=80;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,punto1.class,"g",$line);
    }
    return $result;
  }
}
